- name: disable SWAP
  shell: |
    swapoff -a

- name: disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'

- name: put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: install vmware tools deploypkg
  dnf:
    name: open-vm-tools-deploypkg
    update_cache: yes
    state: present
  
- name: install vmware tools deploypkg
  dnf:
    name: cloud-init
    update_cache: yes
    state: present

