---
- name: install firewalld
  package:
    name: firewalld
    state: present

- name: enable firewalld
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Configure firewalld on worker nodes
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  with_items: '{{ k8s_worker_ports }}'
  tags: node

- name: open flannel ports on the firewall
  firewalld:
    port: "{{ item }}/udp"
    permanent: yes
    state: enabled
  with_items: "{{ flannel_udp_ports }}"