- name: Install kubernetes packages
  dnf:
    name: "{{ item }}"
    disable_excludes: kubernetes
    update_cache: yes
    state: present
  with_items: "{{ kubernetes_packages }}"

- name: Enable kubelet service
  service:
    name: kubelet
    enabled: yes