---

- name: setup dnf
  import_tasks: dnf.yaml
  
- name: setup os
  import_tasks: os-setup.yaml

- name: Configure firewalld
  import_tasks: firewall.yaml

- name: install docker
  import_tasks: docker.yaml

- name: Install k8s
  import_tasks: install_k8s.yaml